# Generated by Django 5.2.16 on 2026-07-09 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Courrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_ordre",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "type_courrier",
                    models.CharField(
                        choices=[
                            ("ENTRANT", "Courrier entrant"),
                            ("SORTANT", "Courrier sortant"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "date_courrier",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="Date d'arrivée ou de départ",
                    ),
                ),
                ("emetteur", models.CharField(max_length=255)),
                ("recepteur", models.CharField(max_length=255)),
                ("objet", models.CharField(max_length=255)),
                ("reference_externe", models.CharField(blank=True, max_length=100)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("RECU", "Reçu"),
                            ("ENREGISTRE", "Enregistré"),
                            ("TRANSMIS", "Transmis"),
                            ("EN_TRAITEMENT", "En traitement"),
                            ("EN_ATTENTE", "En attente"),
                            ("CLOTURE", "Clôturé"),
                            ("ARCHIVE", "Archivé"),
                        ],
                        default="RECU",
                        max_length=20,
                    ),
                ),
                (
                    "urgence",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("URGENT", "Urgent")],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                ("resume", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courriers_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courriers",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Courrier",
                "verbose_name_plural": "Courriers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("commentaire", models.TextField(blank=True)),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                (
                    "courrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="courrier.courrier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'action",
                "verbose_name_plural": "Historique des actions",
                "ordering": ["-date_action"],
            },
        ),
    ]
