# Generated by Django 5.2.16 on 2026-07-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courrier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courrier",
            name="courriers_lies",
            field=models.ManyToManyField(blank=True, to="courrier.courrier"),
        ),
    ]
