# Generated by Django 5.2.16 on 2026-07-12 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_correspondant"),
        ("courrier", "0002_courrier_courriers_lies"),
    ]

    operations = [
        migrations.AddField(
            model_name="courrier",
            name="remarque",
            field=models.TextField(
                blank=True, help_text="Remarque libre (toute information utile)"
            ),
        ),
        migrations.AlterField(
            model_name="courrier",
            name="reference_externe",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Référence"
            ),
        ),
        migrations.AlterField(
            model_name="courrier",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courriers",
                to="core.service",
            ),
        ),
    ]
