# Generated by Django 5.2.16 on 2026-07-09 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("achats", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Marche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("objet", models.CharField(max_length=255)),
                (
                    "type_procedure",
                    models.CharField(
                        choices=[
                            ("AOO", "Appel d'offres ouvert"),
                            ("AOR", "Appel d'offres restreint"),
                            ("CONSULTATION", "Consultation"),
                            ("GRE_A_GRE", "Marché de gré à gré"),
                            ("BON_COMMANDE", "Bon de commande"),
                        ],
                        default="CONSULTATION",
                        max_length=20,
                    ),
                ),
                ("fournisseur", models.CharField(blank=True, max_length=255)),
                (
                    "montant",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("date_lancement", models.DateField(blank=True, null=True)),
                ("date_attribution", models.DateField(blank=True, null=True)),
                ("date_notification", models.DateField(blank=True, null=True)),
                ("date_cloture", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PREPARATION", "Préparation"),
                            ("CONSULTATION_LANCEE", "Consultation lancée"),
                            ("OFFRES_RECUES", "Offres reçues"),
                            ("ANALYSE_OFFRES", "Analyse des offres"),
                            ("ATTRIBUE", "Attribué"),
                            ("NOTIFIE", "Notifié"),
                            ("EN_COURS_EXECUTION", "En cours d'exécution"),
                            ("CLOTURE", "Clôturé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="PREPARATION",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marches_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demande_achat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marches",
                        to="achats.demandeachat",
                    ),
                ),
                (
                    "service_demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marches",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marché",
                "verbose_name_plural": "Marchés",
                "ordering": ["-created_at"],
            },
        ),
    ]
