# Generated by Django 5.2.16 on 2026-07-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marche",
            name="marches_lies",
            field=models.ManyToManyField(blank=True, to="marches.marche"),
        ),
    ]
