# Generated by Django 5.2.16 on 2026-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Correspondant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Correspondant (émetteur / récepteur)",
                "verbose_name_plural": "Correspondants (émetteurs / récepteurs)",
                "ordering": ["nom"],
            },
        ),
    ]
