# Generated by Django 5.2.16 on 2026-07-09 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("objet", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "montant_estimatif",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "type_achat",
                    models.CharField(
                        choices=[
                            ("FOURNITURES", "Fournitures"),
                            ("PRESTATIONS", "Prestations de service"),
                            ("TRAVAUX", "Travaux"),
                            ("MATERIEL_INFORMATIQUE", "Matériel informatique"),
                            ("MAINTENANCE", "Maintenance"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=25,
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("avis_chef_service", models.TextField(blank=True)),
                ("decision_directeur", models.TextField(blank=True)),
                ("date_signature_directeur", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("SOUMISE", "Soumise"),
                            ("VALIDEE_CHEF_SERVICE", "Validée par chef de service"),
                            ("SOUMISE_DIRECTEUR", "Soumise au directeur"),
                            ("SIGNEE_DIRECTEUR", "Signée par directeur"),
                            ("RECUE_BUREAU_ORDRE", "Reçue par le bureau d'ordre"),
                            ("ENREGISTREE", "Enregistrée"),
                            ("TRANSMISE_SERVICE_ACHAT", "Transmise au service achat"),
                            ("EN_COURS_TRAITEMENT", "En cours de traitement"),
                            ("BON_COMMANDE_PREPARE", "Bon de commande préparé"),
                            ("MARCHE_LANCE", "Marché lancé"),
                            ("CLOTUREE", "Clôturée"),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="BROUILLON",
                        max_length=30,
                    ),
                ),
                (
                    "numero_ordre_bo",
                    models.CharField(
                        blank=True,
                        help_text="Numéro d'ordre attribué au bureau d'ordre",
                        max_length=30,
                    ),
                ),
                ("date_enregistrement_bo", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_achat",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'achat",
                "verbose_name_plural": "Demandes d'achat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Approbation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fonction", models.CharField(blank=True, max_length=150)),
                ("date_validation", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROUVE", "Approuvé"),
                            ("REJETE", "Rejeté"),
                            ("A_COMPLETER", "À compléter"),
                            ("EN_ATTENTE", "En attente"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "valideur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approbations",
                        to="achats.demandeachat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approbation",
                "verbose_name_plural": "Approbations",
                "ordering": ["-date_validation"],
            },
        ),
    ]
