# Generated by Django 5.2.16 on 2026-07-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeachat",
            name="circuit",
            field=models.CharField(
                choices=[
                    ("AVEC_ACCORDS", "Avec accords (DCP et autres directions)"),
                    ("LOCALE", "Locale — signature du directeur uniquement"),
                ],
                default="LOCALE",
                help_text="Circuit de validation : avec accords (DCP et autres directions) ou local (signature du directeur uniquement)",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="demandeachat",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon"),
                    ("SOUMISE", "Soumise"),
                    ("VALIDEE_CHEF_SERVICE", "Validée par chef de service"),
                    ("EN_ATTENTE_ACCORDS", "En attente des accords (DCP / directions)"),
                    ("ACCORDS_OBTENUS", "Accords obtenus"),
                    ("SOUMISE_DIRECTEUR", "Soumise au directeur"),
                    ("SIGNEE_DIRECTEUR", "Signée par directeur"),
                    ("RECUE_BUREAU_ORDRE", "Reçue par le bureau d'ordre"),
                    ("ENREGISTREE", "Enregistrée"),
                    ("TRANSMISE_SERVICE_ACHAT", "Transmise au service achat"),
                    ("EN_COURS_TRAITEMENT", "En cours de traitement"),
                    ("BON_COMMANDE_PREPARE", "Bon de commande préparé"),
                    ("MARCHE_LANCE", "Marché lancé"),
                    ("CLOTUREE", "Clôturée"),
                    ("REJETEE", "Rejetée"),
                ],
                default="BROUILLON",
                max_length=30,
            ),
        ),
    ]
