# Generated by Django 5.2.16 on 2026-07-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0002_demandeachat_circuit_alter_demandeachat_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeachat",
            name="demandes_liees",
            field=models.ManyToManyField(blank=True, to="achats.demandeachat"),
        ),
    ]
