# Generated by Django 5.2.16 on 2026-07-09 07:55

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(upload_to=documents.models.document_upload_path),
                ),
                ("nom", models.CharField(blank=True, max_length=255)),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("IMAGE", "Image scannée"),
                            ("WORD", "Word"),
                            ("EXCEL", "Excel"),
                            ("JUSTIFICATIF", "Pièce justificative"),
                            ("DEMANDE_SIGNEE", "Demande signée"),
                            ("BON_COMMANDE", "Bon de commande"),
                            ("CONTRAT", "Contrat"),
                            ("PV", "Procès-verbal"),
                            ("CAHIER_CHARGES", "Cahier des charges"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
